sudo: false
language: python
python:
  - 3.5
services:
  - mysql
before_install:
  - mysql -e "create database IF NOT EXISTS bucketlist_test;" -uroot -proot
install:
  pip install -r requirements.txt
script:
  tox
after_success:
  coveralls
notifications:
  email: false