sudo: false
language: python
python:
  - 3.5
services:
  - mysql
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
before_install:
  - mysql -uroot -proot -e "create database bucketlist_test;" 
install:
  pip install -r requirements.txt
script:
  tox
after_success:
  coveralls
notifications:
  email: false