"""empty message

Revision ID: eb737eb421e7
Revises: cd13f36fb91e
Create Date: 2016-11-03 14:09:15.991002

"""

# revision identifiers, used by Alembic.
revision = 'eb737eb421e7'
down_revision = 'cd13f36fb91e'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import passlib


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_ibfk_1', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'bucketlists', ['bucketlist_id'], ['bucketlist_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_ibfk_1', 'items', 'bucketlists', ['bucketlist_id'], ['bucketlist_id'], ondelete='CASCADE')
    ### end Alembic commands ###
